Fjerner bruk av styled-components/macro da dette ikke funker i modiabrukerdialog.
I modiabrukerdialog får man feil av typen "Uncaught TypeError: macro_1.keyframes is not a function" og alt krasjer

Har prøvd å sette opp babel med babel-plugin-macros i modiabrukerdialog uten at det hjalp, ruller derfor dette tilbake intill videre

Revert "tar i bruk styled-components babel-macro for bedre klassenavn i html"

This reverts commit 1345acc2a6ee00433dfd0ca8e99e888c0847556f.

Revert "rydder opp i imports slik at alle imports av styled components kommer fra '/macro' for å se om det fikser konflikter i modiabrukerdialog"

This reverts commit aeeecbf69277b2fb82ab35790c0e370da9515355.