Fiks feil forårsaket av lite eksplisitt import
I testene, pluss i gamle modiabrukerdialog med nytt visittkort, fikk vi
denne feilen:

Error: Element type is invalid: expected a string (for built-in
components) or a class/function (for composite components) but got:
undefined. You likely forgot to export your component from the file it's
defined in, or you might have mixed up default and named imports.

Løste seg i test ved å spesifisere importen mer nøyaktig